# This is a RayCluster configuration for DOLL
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    # A unique identifier for the head node and workers of this cluster.
  name: raycluster
spec:
  # The version of Ray you are using. Make sure all Ray containers are running this version of Ray.
  rayVersion: '2.34.0'
  ######################headGroupSpec#################################
  # head group template and specs, (perhaps 'group' is not needed in the name)
  headGroupSpec:
    # logical group name, for this called head-group, also can be functional
    # pod type head or worker
    # rayNodeType: head # Not needed since it is under the headgroup
    # the following params are used to complete the ray start: ray start --head --block ...
    rayStartParams:
      dashboard-host: '0.0.0.0'
    #pod template
    template:
      spec:
        nodeSelector:
          eks.amazonaws.com/nodegroup: ps
        containers:
        # The Ray head pod
        - name: doll-head
          image: rayproject/ray:2.34.0
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","pip install torch torchvision"]
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "4"
              memory: "24G"
            requests:
              cpu: "3500m"
              memory: "14G"

  workerGroupSpecs:
  # the pod replicas in this group typed worker
  - groupName: doll-w
    replicas: 64
    minReplicas: 1
    maxReplicas: 64
    # logical group name, for this called small-group, also can be functional
    
    rayStartParams: {}
    #pod template
    template:
      metadata:
        labels:
          key: value
        # annotations for pod
        annotations:
          key: value
      spec:
        nodeSelector:
          eks.amazonaws.com/nodegroup: workers
        containers:
        - name: doll-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayproject/ray:2.34.0
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","pip install torch torchvision"]
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "2"
              memory: "24G"
            requests:
              cpu: "1500m"
              memory: "1G"
  - groupName: doll-ts
    replicas: 1
    minReplicas: 1
    maxReplicas: 1
    # logical group name, for this called small-group, also can be functional
    
    rayStartParams: {}
    #pod template
    template:
      metadata:
        labels:
          key: value
        # annotations for pod
        annotations:
          key: value
      spec:
        nodeSelector:
          eks.amazonaws.com/nodegroup: ts
        containers:
        - name: doll-test # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayproject/ray:2.34.0
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh","-c","pip install torch torchvision"]
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          resources:
            limits:
              cpu: "8"
              memory: "24G"
              #gpu: "1"
            requests:
              cpu: "3500m"
              memory: "14G"
              #gpu: "1"